language: ruby

branches:
    only:
        - master
        - develop

rvm:
    - 2.3.3

install:
    - bundle install --without production

before_script:
    - rails db:migrate:reset

script:
    - bundle exec rspec
