# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e41f30370faac7a6d166620e195ce647453bb6a18d2f5adb7626b3fc342f1e89c19c34599b360a750ce9bcaa125b7054c08752505f7020cdfb7fff3bd8fe06

test:
  secret_key_base: cbe51a4ae3cc62ef8328ee96a4f944b376708e106034a0c8bb49d70ca4c8a6ea81c1a223f9549ac5a2db8cbee406e06eeb25fe436466ed642ee7fe96deab5ac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
